
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqbtwarnufgfjzuxlhms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxYnR3YXJudWZnZmp6dXhsaG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDk4ODUsImV4cCI6MjA1ODAyNTg4NX0.BwE3HIwOVmilnpZQNHF8IXKyDhKBk8Z1_pa9MnL8mrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
